development:
  bucket_name: zut001
  access_key_id: G5sUrL1jzw1ExhU2WIjJ
  secret_access_key: NHv1TBn43wMpsvBLI5FqgOYLakwCZe96ELmFlQou
  region: us-east-1
  force_path_style: false #If your storage use path-style bucket addresses.
  endpoint: 'http://39.99.249.87:9000'

test:
  bucket_name: zut001
  access_key_id: ZP1E5h7Ibp8m03NsRlco
  secret_access_key: Dy2XmyJrsL4UGp6EfY7O4AIIgL870DqJuTHYKLdr
  region: us-east-1
  force_path_style: true #If your storage use path-style bucket addresses.
  endpoint: 'http://39.99.249.87:9000'

production:
  bucket_name: zut001
  access_key_id: ZP1E5h7Ibp8m03NsRlco
  secret_access_key: Dy2XmyJrsL4UGp6EfY7O4AIIgL870DqJuTHYKLdr
  region: us-east-1
  force_path_style: true #If your storage use path-style bucket addresses.
  endpoint: 'http://39.99.249.87:9000'
