default: &default
  bucket_name: <%= ENV.fetch('S3_BUCKET_NAME') %>
  access_key_id: <%= ENV.fetch('S3_AK') %>
  secret_access_key: <%= ENV.fetch('S3_SK') %>
  region: <%= ENV.fetch('S3_REGION', 'us-east-1') %>
  force_path_style: true #If your storage use path-style bucket addresses.
  endpoint: <%= ENV.fetch('S3_ENDPOINT') %>
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
