default: &default
  adapter: <%= ENV.fetch('DB_DRIVER') %>
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  timeout: 5000

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'canvas_production') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'canvas_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'canvas_test') %>
