name: 发布正式版

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  repository_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "DATE=$(date '+%Y-%m-%d.%H')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile-prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/canvas-lms-prod:latest,${{ secrets.DOCKERHUB_USERNAME }}/canvas-lms-prod:${{ github.ref_name }}
          push: true
